### POST contract cycle

POST {{host}}/contracts
Content-Type: application/json

{
    "name": "123",
    "shift": {
      "duration": 12,
      "id": 2,
      "startDate": "2026-04-22T16:29:59.457Z",
      "startTime": "2026-04-22T09:00:00.000Z",
      "customDays": null
    }
}

### POST contract custom

POST {{host}}/contracts
Content-Type: application/json

{
  "name": "Контракт №2",
  "shift": {
    "duration": 12,
    "id": 1,
    "startDate": null,
    "startTime": "2026-04-22T10:00:00.000Z",
    "customDays": [
      {
        "type": "workday",
        "weeknumber": 0
      },
      {
        "type": "workday",
        "weeknumber": 1
      },
      {
        "type": "workday",
        "weeknumber": 2
      },
      {
        "type": "workday",
        "weeknumber": 3
      },
      {
        "type": "workday",
        "weeknumber": 4
      },
      {
        "type": "weekend",
        "weeknumber": 5
      },
      {
        "type": "weekend",
        "weeknumber": 6
      }
    ]
  }
}

### get contract by id

GET {{host}}/contracts/1
Content-Type: application/json; charset=utf-8;

### delete contract by id

DELETE {{host}}/contracts/4
Content-Type: application/json; charset=utf-8;

### get contracts

GET {{host}}/contracts
Content-Type: application/json; charset=utf-8;

### assign

POST {{host}}/contracts/1/assign
Content-Type: application/json

{
  "employee": {
    "fullname": "Лозовой Борис Сергеевич",
    "id": 678937
  }
}