export enum RolesType {
  authApi = "auth-api",
  roleApi = "role-api",
  selectLanguage = "sl",
  interfaceLanguageEn = "len",
  roleApiGroup = "role-api_g",
  recruiter = "recruiter",
  controlUsersGroupDownload = "cu_grp_d",
  consultingRoleUser = "consulting-role-user",
  consultingRoleManager = "consulting-role-manager",
  consultingRoleManagerClone = "consulting-role-manager_clone",
  consultingRoleUserExtended = "consulting-role-user_extended",
  consultingRoleViewSession = "cnslt-usr-vw-s",
  consultingRoleViewOrganization = "cnslt-usr-vw-o",
  consultingRoleUserCourier = "cnslt-usr_c",
  consultingRoleInstallmentsLimit = "cnslt_inst-l",
  consultingRoleSearchPhone = "cnslt-srch-phn",
  supplierThemeGroupsAdmin = "thm_grp_a",
  supplierThemeGroupsClientsAdmin = "cus-com-admin",
  customerCommAdmin = "customer-comm-admin",
  supplierCommAdmin = "supplier-comm-admin",
  supplierBankCommAdmin = "bank-comm-admin",
  supplierCommAdminTags = "sup-com-a_t",
  supplierCommAdminNotification = "sup-com-a_ntf",
  suppliersCommAdminTabLocales = "sup-com_lcl",
  courierInfoFull = "courier_info-f",
  cmsApi = "cms-api",
  cmsApiPartnerssupport = "cms-api_partnerssupport",
  cmsApiWbtravel = "cms-api_wbtravel",
  cmsApiOrr = "cms-api_orr",
  cmsApiGkko = "cms-api_gkko",
  cmsApiCustomermain = "cms-api_customermain",
  cmsApiOnf = "cms-api_onf",
  cmsApiBy = "cms-api_by",
  cmsApiCollectors = "cms-api_collectors",
  cmsApiEwallet = "cms-api_ewallet",
  cmsButtonQueue = "cms_button-queue",
  cmsApiInteractive = "cms-api-interactive",
  cmsApiInteractiveSeven = "cms-api-interactive_seven",
  cmsApiInteractiveKontaktServis = "cms-api-interactive_kontakt_servis",
  cmsApiRedline = "cms-api_redline",
  cmsApiCourierSupport = "cms-api_couriersupport",
  cmsApiWarehousehr = "cms-api_warehousehr",
  cmsApiDefault = "cms-api_default",
  cmsApiCustomerRu = "cms-api_customerru",
  cmsApiCustomerBy = "cms-api_customerby",
  cmsApiCustomerProblemBy = "cms-api_customerproblemsby",
  cmsApiTravel = "cms-api_travel",
  cmsApiBankServiceB2b = "cms-api_bank_service_b2b",
  cmsApiBankServiceB2c = "cms-api_bank_service_b2c",
  deliveryNotification = "dn",
  deliveryNotificationAutocancel = "dn_ac",
  deliveryNotificationMassClose = "dn_ms_cls",
  notificationAdmin = "notification-admin",
  interceptionApi = "interception-api",
  interceptionApiSuppliers = "interception-api_suppliers",
  interceptionApiSuppliersHr = "interception-api_suppliers_hr",
  interceptionApiSuppliersOrrhr = "interception-api_suppliers_orrhr",
  interceptionApiSuppliersCustomermain = "interception-api_suppliers_customermain",
  interceptionApiSuppliersPartnerssupport = "interception-api_suppliers_partnerssupport",
  interceptionApiSuppliersOrr = "interception-api_suppliers_orr",
  interceptionApiSuppliersOnf = "interception-api_suppliers_onf",
  interceptionApiSuppliersGkko = "interception-api_suppliers_gkko",
  interceptionApiSuppliersWbtrabel = "interception-api_suppliers_wbtravel",
  interceptionApiSuppliersCollectors = "interception-api_suppliers_collectors",
  interceptionApiSuppliersEwallet = "interception-api_suppliers_ewallet",
  interceptionApiSuppliersRedline = "interception-api_suppliers_redline",
  interceptionApiSuppliersWarehousehr = "interception-api_suppliers_warehousehr",
  interceptionApiSuppliersCourierSuppoer = "interception-api_suppliers_couriersupport",
  interceptionApiPickup = "interception-api_pickup",
  interceptionApiOffice = "interception-api_office",
  interceptionApiVoice = "interception-api_voice",
  interceptionApiSupportPickup = "interception-api_supportpickup",
  interceptionApiSenior = "interception-api-senior",
  interceptionApiSuppliersDefault = "interception-api_suppliers_default",
  interceptionApiSuppliersCustomerru = "interception-api_suppliers_customerru",
  interceptionApiSuppliersCustomerby = "interception-api_suppliers_customerby",
  interceptionApiSuppliersCustomerproblemsby = "interception-api_suppliers_customerproblemsby",
  interceptionApiSuppliersTravel = "interception-api_suppliers_travel",
  interceptionApiBankServiceB2b = "interception-api_bank_service_b2b",
  interceptionApiBankServiceB2c = "interception-api_bank_service_b2c",
  customerDeptDeliveryRemoveUser = "customer-dept_delivery_remove_user",
  customerDeptDeliveryRemoveManager = "customer-dept_delivery_remove_manager",
  track = "track",
  trackAdmin = "track_admin",
  trackAdminPp = "track_admin_pp",
  trackAdminEduwb = "track_admin_eduwb",
  trackModerator = "track_moderator",
  trackDeveloper = "track_developer",
  ccTrack = "cc-track",
  ppTrack = "pp-track",
  trackEduwb = "track-eduwb",
  pickupMaps = "pickup-maps",
  phone = "phone",
  activeDeliveriesManager = "active-deliveries-manager",
  activeDeliveriesCanceller = "active-deliveries_canceller",
  activeDeliveriesCancellerDkb = "act-dlvr_cc_dkb",
  activeDeliveriesClone = "active-deliveries_clone",
  activeDeliveriesExtension = "active-deliveries_extension",
  activeDeliveriesCheckLk = "active-deliveries_checklk",
  activeDeliveriesMover = "active-deliveries_mover",
  msgSender = "msg-sender",
  msgSenderManager = "msg-sender_manager",
  senior = "senior",
  seniorEntryOffer = "senior-entry_offer",
  seniorEntryOfferExtended = "senior-entry_offer-extended",
  seniorEntryCreatedApplications = "senior-entry_created-applications",
  seniorEntryСancelPosition = "senior-entry_cancel-position",
  seniorEntrySupportClient = "sen-e_sc",
  seniorEntrySupportClientStats = "sen-e_sc_s",
  seniorEntrySupportRatings = "sen-e_sc_r",
  seniorEntrySupportCategoryRatings = "sen-e_sc_r_ctg",
  seniorEntryBlacklist = "sen-e_bl",
  seniorEntryIvr = "sen-ivr",
  seniorEntryIvrAlarm = "sen-ivr-alarm",
  seniorEntryCommClose = "sen-e_ccf",
  seniorEntryCallbot = "sen-callbot",
  seniorEntryCallbotAlertsServices = "sen-alarm",
  seniorEntryCallbotPanicButton = "panic_button",
  seniorEntryDictionaryAdmin = "sen-e_dct_a",
  seniorEntryDictionaryAdminDelete = "sen-e_dct_a_d",
  seniorEntryAppealsCustomers = "sen-e_apls_ct",
  seniorEntryNotifications = "sen-t_ntf",
  seniorEntrySellersShowcase = "sen_shwc",
  seniorEntryCustomerShowcase = "cus_shwc",
  seniorEntryCustomerShowcaseClientProfile = "cus_sh_crd",
  seniorDictionary = "sen-e_dct",
  seniorEditTemplate = "sen-edt_tpl",
  seniorTokenServiceAdmin = "sen-tkn_a",
  classificator = "classificator",
  classificatorManager = "classificator-manager",
  digitalSupplier = "dgtl",
  digitalSupplierBlockedButton = "dgtl_lock",
  deliveryControl = "delivery-control",
  deliveryChangeDstOffice = "delivery_change_dst_office",
  blacklistCouriers = "blacklist-couriers",
  bankAdmin = "b_admin",
  bankFl = "b_fl",
  bankFlSearch = "b_fl-s",
  bankSme = "b_SME",
  bankSmeSearch = "b_SME-s",
  bankAppeals = "b_appeals",
  bankBlockedCard = "b_block_card",
  messengers = "messengers",
  messengersManager = "messengers_manager",
  messengersStatistics = "mess_stat",
  messChatPremium = "mess-cht_prm",
  supplierCardUser = "supplier-card_user",
  supplierCardManager = "supplier-card_manager",
  suppliersCommunications = "suppliers-communications",
  suppliersCommunicationsStatuses = "s-com_sts",
  suppliersCommunicationsNew = "s-com_n",
  suppliersCommunicationsReopen = "s-com_r",
  suppliersCommunicationsVip = "s-com_pr",
  suppliersCommunicationsBank = "s-com_bank",
  suppliersCommunicationsPriority = "s-com_prrt",
  suppliersCommunicationsExtended = "suppliers-communications-extended",
  suppliersCommunicationsExtendedAnswer = "suppliers-communications-extended_answer",
  suppliersCommunicationsExtendedAnswerOld = "sc-e_a_ol",
  suppliersCommunicationsChatTheme = "suppliers-communications_chat-theme",
  suppliersCommunicationsChatReopen = "suppliers-communications_chat-reopen",
  suppliersCommunicationsEscalationProduct = "sup-com_escalation-product",
  suppliersCommunicationsEscalationSD = "sup-dlg_escl-sd",
  suppliersCommunicationsChatClose = "sc_cht-cls",
  suppliersCommunicationsChatOperatorHelp = "seller_operator_help",
  suppliersCommunicationsChatTags = "sup-com_c-t",
  suppliersCommunicationsChatGetWork = "sup-com_claim_postponed_dialog",
  suppliersCommunicationsSystemThemes = "sup-com_sys-thm",
  suppliersCommunicationsChatSystemThemes = "sc-cht_sys-thm",
  suppliersCommunicationsAutoGet = "sup-com_auto_get",
  suppliersCommunicationsAutoGetSearch = "sup-com_auto_get_s",
  suppliersCommunicationsAutoGetPremium = "sup_auto_g_p",
  suppliersCommunicationsMassBot = "sup-com_mas-bot",
  suppliersCommunicationsChatEscalade = "sc-cht_escl",
  communications = "communications",
  communicationsIntern = "communications_intern",
  communicationsManager = "communications_manager",
  communicationThemeSearch = "communications-theme-search",
  communicationThemeWhEmpl = "communications-theme-wh-empl",
  communicationThemeAvi = "communications-theme_avi",
  communicationWbCard = "communications-theme_card-wb",
  communicationWbJobs = "communications-theme_wbjobs",
  communicationReplacement = "com-thm_repl",
  communicationPodmeny = "com-thm_pdn",
  communicationsThemePvz = "communications-theme_pvz",
  communicationsThemePvzOperator = "comms-thm_pvz_op",
  communicationThemeWhEmplWish = "communications-theme-wh-empl-wish",
  communicationWbWarehouse = "communications-wb_warehouse",
  communicationsThemeErrorWrite = "communications-theme_error-write",
  communicationWbPvz = "communications-wb_pvz",
  communicationChatCategory = "communications-chat-category",
  communicationChatTravel = "comm-ch-t",
  communicationChatTravelPp = "comm-ch-tp",
  communicationChatWbgo = "comm-ch-wg",
  communicationChatPvz = "comm-ch-pvz",
  communicationChatESG = "comm-ch-esg",
  communicationChatCourier = "comm-ch-crr",
  communicationChatTour = "comm-ch-tour",
  communicationChatRealty = "comm-ch-realty",
  communicationChatEapteka = "comm-ch-phrm",
  communicationsCopyright = "communications-copyright",
  communicationsCopyrightUnassignAppeal = "m_cro_as",
  communicationsCopyrightAdmin = "cmm_cprt_a",
  communicationsSuppliersExt = "communications-suppliers-ext",
  communicationIssues = "comm_iss",
  communicationChatPremium = "comm-cht_prm",
  communicationThemeOspBrak = "comm-thm_osp-brk",
  reportSuppliers = "report-suppliers",
  heads = "heads",
  reportCouriersCarry = "report-couriers-carry",
  gkko = "gkko",
  gkkoActiveSessions = "gkko_active_sessions",
  gkkoProblemMistake = "gk_p_m",
  gkkoChargebackEdit = "gkko_chargeback-edit",
  gkkoIB = "gk_ib",
  gkkoMvd = "gk_mvd",
  gkkoBreaking = "gk_brkg",
  gkkoMvdLawyer = "gk_mvd_l",
  gkkoMvdOperator = "gk_mvd_o",
  gkkoWbBank = "gk_bnk",
  gkkoAntifraud = "gk_antifraud",
  giftCerv = "gift_sert",
  feedbacks = "fb",
  feedbacksModerator = "fb_mod",
  feedbacksSuperModerator = "fb_smod",
  feedbacksSupplier = "fb_supplier",
  feedbacksSupervisor = "fb_supervisor",
  feedbacksTyping = "fb_typing",
  financeOperations = "finance-operations",
  financeReturnServices = "finance-return-services",
  financeSearchPayments = "finance-search-payments",
  financeReportAdjustments = "finance-report-adjustments",
  financeReportConveyor = "finance-report-conveyor",
  financeReportRefundConveyorAdmin = "finance-report-conveyor_admin",
  financeReportCredit = "finance-report-credit",
  financeReportRefund = "finance-report-refund",
  financeReportCustomer = "finance-report-customer",
  financeReportUnlockRefund = "finance-report_unlock-refund",
  financeReportCustomerReceipt = "finance-report_customer-receipt",
  financeReportCustomerSetCsp = "finance-report_customer-set-csp",
  financeReportGatewayRepolling = "finance-report_gateway-repolling",
  financeReportBalanceReverse = "finance-report_balance-reverse",
  financeReportCreateCheck = "finance-report_create-check",
  financeConveyorRefundServices = "finance-conveyor_refund-services",
  financeFiscalizePayment = "finance-fiscalize-payment",
  finance3dsDeleteCard = "finance-3ds_delete-card",
  financeUserCards = "finance-user-cards",
  financeServiceCancel = "fin_ser-can",
  financeSubscriptionRefund = "fin_s-r",
  customerFraud = "customer-fraud",
  customerFraudRating = "customer-fraud-rating",
  customerCancelSession = "cus-c-s",
  customerBlockEWallet = "cus-b-ew",
  customerEntryPvzRefund = "cstmr_pvz_ref",
  customerLotteryRefund = "ctmr_ltr",
  reportBookkeeping = "report-bookkeeping",
  complaintPvz = "complaint-pvz",
  kbtZones = "kbt-zones",
  reportKbt = "report-kbt",
  problemChangeState = "problem_change_state",
  problemPPVz = "prblms_tck",
  accountPaymentsSenior = "account-payments-senior",
  reportCalls = "report-calls",
  reportCallsOparetorsOutsources = "report-calls_operators_outsources",
  reportKeyWord = "report-key-word",
  worldCardUser = "worldCardUser",
  reportWorldSmId = "report-world-smid",
  reportCourierDelivery = "report-courier-delivery",
  orrFranchise = "orr-franchise",
  operationDetalCreateRefund = "operation-detal_create_refund", // возможно убрать
  operationDetalRequisitions = "operation-detal_requisitions",
  operationDetalAdjOther = "operation-detal_adjust_other",
  operationDetalAdj = "operation-detal_adjust",
  operationDetalRefundSelectEarlier = "operation-detal_refund_select_earlier",
  operationDetalDeleteCard = "operation-detal_delete_card",
  operationDetalRefundBalanceToReq = "op-d_r-b-q",
  operationDetalHistoryBalance = "operation-detal_history-balance", // возможно убрать
  operationDetalWbBank = "op-dtl_wbb",
  operationDetalCrypto = "op-dtl_crypto",
  reportQueueComplaints = "report-queue-complaints",
  reportReadyCourier = "report-ready-courier",
  reportCommunications = "report-communications",
  reportEfficiencyIvr = "report-efficiency-ivr",
  reportCallsOutsource = "report-calls-outsource",
  reportWarehouseHB = "report-warehouse-hb",
  reportFoodCity = "report-food-city",
  reportWorldCanceling = "report-world-canceling",
  reportArticleInfo = "report-article-info",
  reportRidHistory = "report-rid-history",
  reportSupplierComms = "report-supplier-comms",
  newsPortalAdmin = "news-portal_admin",
  reportInteractiveSeven = "report-interactive-seven",
  reportInteractiveKontaktServis = "report-interactive-kontakt-servis",
  payroll = "payroll",
  payrollAdmin = "payroll_admin",
  payrollPpUser = "payroll_pp-user",
  payrollSelfUser = "payroll_self-user",
  payrollMainFactors = "payroll_main-factors",
  payrollTariffication = "payroll_tariffication",
  payrollPayment = "payroll_payment",
  payrollPaymentManualData = "payroll_payment-manual-data",
  payrollPMData = "prl_pm_d",
  payrollPMAddData = "prl_pm_ad",
  payrollExcess = "payroll_excess",
  payrollKuk = "payroll_kuk",
  payrollRewards = "payroll_rewards",
  payrollClaims = "prl_clms",
  payrollReports = "prl_rpts",
  payrollReportsEmployee = "prl_rpts_empl",
  payrollReportsSalary = "prl_rpts_slr",
  payrollReportsAutodisable = "prl_rpts_athdsb",
  pvzConsulting = "pvz_crd_u",
  pvzConsultingAdmin = "pvz_crd_m",
  pvzConsultingContacts = "pvz_crd_cntct",
  pvzInformingAdmin = "pvz_inf_a",
  transferHistory = "trfr_h",
  test = "test",
  uiKit = "ui-kit",
  ccTraining = "cc-training",
  staffRecruitment = "staff-recruitment",
  unloadingSellers = "unloading-sellers",
  writeOffs = "write-offs",
  writeOffsPodmeny = "wr-of_pod",
  writeOffsFines = "wr-of_fin",
  writeOffsShkRb = "wr-of_rb",
  travelAdmin = "travel-admin",
  travelAdminTrip = "trvl-a_trp",
  travelAdminTripQa = "trvl-a_trp_qa",
  travelAdminModeratorComments = "trvl-a_m-com",
  travelAdminCommissions = "trvl-a_prcng",
  travelAdminOrdersPassport = "trvl-a_o_p",
  travelAdminOrderConstrols = "trvl-a_o_c",
  travelAdminAdventure = "trvl-a_adv",
  travelAdminReporting = "trvl-a_rprt",
  travelAdminReportingInsurance = "trvl-a_rprt-ins",
  travelAdminManualRefund = "trvl-a_mnlrfnd",
  travelAdminFunAndSun = "trvl_fns",
  travelAdminAviaRefund = "avia-admin-manualrefund",
  scOperator = "sc-operator",
  scSupervisor = "sc-supervisor",
  supplierEnrtyRefundHistory = "sp_rfnd",
  supplierEntryPurchaseSupplies = "sp-e_prcs-spls",
  supplierEntryPurchaseNmInfo = "sp-e_prcs-nm",
  supplierEntryPurchaseShkInfo = "sp-e_prcs-shk",
  supplierEntryCredit = "sp_crdts",
  supplierEntryNotifications = "sp_notif",
  supplierEntrySupplies = "sp_suppl",
  supplierEntryRegistration = "sp_main_registration",
  supplierEntryRegistrationWaitActPA = "sp_main_activation-invoice",
  supplierEntryRegistrationDeleteInvoice = "sp_main_delete-invoice",
  supplierEntryDocuments = "sp_docs",
  supplierEntryDocumentsSendDocs = "sp_docs_send",
  supplierEntryDocumentsEDM = "sp_docs_edo",
  supplierEntryGoodsCard = "sp_goods-card",
  supplierEntryGoodsCardBanHistory = "sp_ban-history",
  supplierEntryItemStatusStockWb = "sp_sts",
  supplierEntryFinance = "sp_finance",
  supplierEntryWithdrawalsFundsNB = "sp_finance_payments",
  supplierEntryChangingStatusesShK = "sp_finance_sale-status",
  supplierEntryCheckingWriteOffs = "sp_sts_inv_lost",
  supplierEntryCheckingFines = "sp_fines",
  supplierEntryCheckingProblemProduct = "sp-prblm_prdct",
  supplierEntryCheckShK = "sp_shk_chck",
  supplierEntryCheckCompensation = "suppliers-communications_dispute",
  supplierEntryCheckCompensationAdmin = "suppliers-communications_dispute-admin",
  supplierEntryCheckPackaging = "sp_pkg_dpt",
  supplierEntrySuppliesMrOrders = "sp_supll_orders",
  supplierEntryPenaltyForDimensions = "pen_dim",
  supplierEntryBlockingCar = "sp_blck-vhcl",
  supplierEntryRefunds = "sp_rtrns",
  supplierEntryRefundsRequest = "sp_rtrns_claims",
  supplierEntrySupManagement = "sp-main-mng",
  suppelierOwnerIdView = "sup_ownerid",
  superAdmin = "super-admin",
  chNoCustomerSearch = "ch_no_customer_search",
  chCustomerSearch = "ch&customer_search",
  grCustomerSearch = "gr&customer_search",
  lkPackage = "tst-pkg",
  mail = "mail",
  mailSend = "mail_send",
  mailComments = "mail-comments",
  knowledgeBaseAdmin = "kb_a",
  knowledgeBaseUnlock = "kb_unlock",
  knowledgeBaseEnglish = "kb_en",
  knowledgeBaseChinese = "kb_cn",
  knowledgeBaseGeorgian = "kb_ge",
  testSearch = "tst_s",
  errorWebCC = "error_veb-kc",
  wbСonnectionOperator = "wb_con_o",
  wbConnectionLead = "wb_con_l",
  wbConnectionAdmin = "wb_con_a",
  outgoingCallsAdmin = "Admin_PR",
  outgoingCallsOperator = "oprtr_PR",
  categoryChatPvzPpvz = "operator_ppvz",
  categoryChatPvzFpvz = "operator_fpvz",
  supplierCardPretrialClaims = "sc_p-trl_r",
  rolePaymentMPM = "fn_payment-mpm",
  roleReturnsMPM = "fn_returns-mpm",
  financeRefundForSubscriber = "fn_frfs",
  notificationRo = "notification-ro",
  supportMAds = "sup-m_ads",
  suppAdjAppeals = "sup-adj-apls",
  suppAdjAppealsAdmin = "sup-adj-apls_a",
  adminWFM = "admin_wfm",
  userWFM = "user_wfm",
  wbTaxiChat = "wb-taxi_m",
  customerWbTaxi = "wb-taxi_c",
  wbTaxiAdministrate = "wb-taxi_a",
  wibes = "wibes",
  wbTrack = "wb-track",
  qaAdmin = "qa_admin",
  qaManager = "qa_manager",
  qaCreator = "qa_creator",
  testBankStun = "test-bank-stun",
  bankDictionaryAppeals = "b_dct-apls",
  qaSupervisor = "qa_sv",
  operatorHelp = "operator_help",
  mailAdmin = "mail-admin",
  eApteka = "E_APTEKA",
  phoneShowFullNumber = "phone-show",
  operatorUz = 'oprtr-uz'
}

// export const ROLE_PACKAGE = {
//   admin: [
//     RolesType.authApi,
//     RolesType.roleApi,
//     RolesType.heads,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//     RolesType.consultingRoleUserExtended,
//     RolesType.consultingRoleManager,
//     RolesType.track,
//     RolesType.trackAdmin,
//     RolesType.trackDeveloper,
//     RolesType.trackModerator,
//     RolesType.notificationAdmin,
//     RolesType.classificator,
//     RolesType.classificatorManager,
//     RolesType.supplierCardManager,
//     RolesType.msgSenderManager,
//     RolesType.customerFraudRating,
//     RolesType.operationDetalRequisitions,
//     RolesType.activeDeliveriesCanceller,
//     RolesType.kbtZones,
//   ],
//   operator: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//     RolesType.communicationsIntern,
//     RolesType.lkPackage
//   ],
//   operatorIncomingCall: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//     RolesType.phone,
//     RolesType.lkPackage
//   ],
//   senior: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.communicationsManager,
//     RolesType.messengers,
//     RolesType.messengersManager,
//     RolesType.phone,
//     RolesType.financeOperations,
//     RolesType.cmsApi,
//     RolesType.cmsApiCustomermain,
//     RolesType.cmsApiGkko,
//     RolesType.cmsApiOnf,
//     RolesType.cmsApiOrr,
//     RolesType.cmsApiWbtravel,
//     RolesType.cmsApiPartnerssupport,
//     RolesType.cmsButtonQueue,
//     RolesType.customerDeptDeliveryRemoveManager,
//     RolesType.accountPaymentsSenior,
//     RolesType.reportBookkeeping,
//     RolesType.reportCalls,
//     RolesType.reportCommunications,
//     RolesType.reportCourierDelivery,
//     RolesType.reportEfficiencyIvr,
//     RolesType.reportKbt,
//     RolesType.reportKeyWord,
//     RolesType.reportQueueComplaints,
//     RolesType.reportReadyCourier,
//     RolesType.reportSuppliers,
//     RolesType.reportWorldSmId,
//     RolesType.senior,
//     RolesType.financeReportAdjustments,
//     RolesType.interceptionApi,
//     RolesType.interceptionApiOffice,
//     RolesType.interceptionApiPickup,
//     RolesType.interceptionApiSuppliers,
//     RolesType.interceptionApiSuppliersGkko,
//     RolesType.interceptionApiSuppliersHr,
//     RolesType.interceptionApiSuppliersOnf,
//     RolesType.interceptionApiSuppliersOrr,
//     RolesType.interceptionApiSuppliersOrrhr,
//     RolesType.interceptionApiSuppliersPartnerssupport,
//     RolesType.interceptionApiSuppliersWbtrabel,
//     RolesType.interceptionApiSupportPickup,
//     RolesType.interceptionApiVoice,
//     RolesType.activeDeliveriesManager,
//     RolesType.activeDeliveriesExtension,
//     RolesType.activeDeliveriesMover,
//     RolesType.orrFranchise,
//     RolesType.msgSender,
//     RolesType.financeReportRefund,
//     RolesType.financeReportConveyor,
//     RolesType.deliveryChangeDstOffice,
//     RolesType.activeDeliveriesCheckLk,
//   ],
//   operatorWorld: [
//     RolesType.authApi,
//     RolesType.worldCardUser,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//   ],
//   sellers: [
//     RolesType.authApi,
//     RolesType.supplierCardUser,
//     RolesType.suppliersCommunications,
//     RolesType.suppliersCommunicationsExtended,
//     RolesType.consultingRoleUser,
//   ],
//   gkko: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//     RolesType.gkko,
//     RolesType.activeDeliveriesMover,
//     RolesType.financeReportCustomer,
//     RolesType.operationDetalAdj,
//     RolesType.orrFranchise,
//     RolesType.blacklistCouriers,
//     RolesType.activeDeliveriesExtension,
//     RolesType.reportQueueComplaints,
//     RolesType.reportReadyCourier,
//     RolesType.deliveryControl,
//     RolesType.complaintPvz,
//     RolesType.pickupMaps,
//     RolesType.deliveryChangeDstOffice,
//     RolesType.reportCourierDelivery,
//     RolesType.activeDeliveriesManager,
//     RolesType.activeDeliveriesCheckLk,
//     RolesType.reportCouriersCarry,
//     RolesType.reportKbt
//   ],
//   training: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//     RolesType.interceptionApi,
//     RolesType.interceptionApiOffice,
//     RolesType.interceptionApiPickup,
//     RolesType.interceptionApiSuppliers,
//     RolesType.interceptionApiSuppliersGkko,
//     RolesType.interceptionApiSuppliersHr,
//     RolesType.interceptionApiSuppliersOnf,
//     RolesType.interceptionApiSuppliersOrr,
//     RolesType.interceptionApiSuppliersOrrhr,
//     RolesType.interceptionApiSuppliersPartnerssupport,
//     RolesType.interceptionApiSuppliersWbtrabel,
//     RolesType.interceptionApiSupportPickup,
//   ],
//   finance: [
//     RolesType.authApi,
//     RolesType.financeOperations,
//     RolesType.financeReportCustomer,
//     RolesType.consultingRoleUser,
//     RolesType.communications,
//     RolesType.messengers,
//     RolesType.phone,
//     RolesType.operationDetalAdjOther,
//   ],
//   other: [
//     RolesType.authApi,
//     RolesType.consultingRoleUser,
//   ]
// }
